AIDA.Master.Web/Controllers/CollectionController.cs
using AIDA.Master.Infrastucture.Constants;
using AIDA.Master.Service.Businesses;
using AIDA.Master.Service.Localizations;
using AIDA.Master.Service.Models;
using AIDA.Master.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AIDA.Master.Web.Controllers
{
    [AuthenticationActionFilter(ModuleCode.ImportCollection)]
    public class CollectionController : Controller
    {
        // GET: Collection
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Import(ImportCollectionModel model)
        {
            AlertMessage alert = new AlertMessage();

            CollectionBusiness business = new CollectionBusiness();

            alert = business.ImportCollection(model);

            return RedirectToAction("Index");
        }
    }
}

AIDA.Master.Web/Controllers/HierSalesController.cs
using AIDA.Master.Infrastucture.Constants;
using AIDA.Master.Infrastucture.MailService;
using AIDA.Master.Service.Businesses;
using AIDA.Master.Service.Localizations;
using AIDA.Master.Service.Models;
using AIDA.Master.Web.Attributes;
using AIDA.Master.Web.Filters;
using Radyalabs.Core.Helper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AIDA.Master.Web.Controllers
{
    [AuthenticationActionFilter(ModuleCode.MasterSalesHier)]
    public class HierSalesController : Controller
    {
        public ActionResult Index()
        {
            HierSalesBusiness business = new HierSalesBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            ViewBag.IsEditable = business.IsEditable();

            return View();
        }

        [HttpPost]
        public ActionResult DatatableIndex(JDatatableViewModel model)
        {
            if (!Request.IsAjaxRequest())
            {
                return RedirectToAction("Index");
            }

            JDatatableResponse resp = new JDatatableResponse();

            HierSalesBusiness business = new HierSalesBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            resp = business.GetDatatable(model);

            return new MyJsonResult(resp, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Rayon(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }

            ViewBag.Rayon = id;

            return View();
        }

        [HttpPost]
        public ActionResult DatatableRayon(RayonDatatableViewModel model)
        {
            if (!Request.IsAjaxRequest())
            {
                return RedirectToAction("Index");
            }

            JDatatableResponse resp = new JDatatableResponse();

            HierSalesBusiness business = new HierSalesBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            resp = business.GetDatatableCustomer(model);

            return new MyJsonResult(resp, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ExportSales(JDatatableViewModel model)
        {
            HierSalesBusiness business = new HierSalesBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            AlertMessage alert = business.ExportSalesToExcel(model);

            if (alert.Status == 1)
            {
                var bytes = alert.Data as byte[];

                return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, string.Format("HirarkiSales-{0}.xlsx", DateTime.UtcNow.ToUtcID().ToString("yyyyMMdd-HHmm")));
            }

            return RedirectToAction("Index");
        }

        public ActionResult ImportSales()
        {
            HierSalesBusiness business = new HierSalesBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            if (!business.IsEditable())
            {
                TempData["AlertMessage"] = new AlertMessage(StaticMessage.ERR_ACCESS_DENIED);

                return RedirectToAction("Index");
            }

            List<HierSalesViewModel> model = null;

            if (TempData["_Data"] != null)
            {
                model = TempData["_Data"] as List<HierSalesViewModel>;
            }

            return View(model);
        }

        public ActionResult PreviewImportSales()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PreviewImportSales(ImportSalesViewModel model)
        {
            AlertMessage alert = new AlertMessage();

            if (!ModelState.IsValid)
            {
                alert.Text = string.Join(System.Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
            }
            else
            {
                HierSalesBusiness business = new HierSalesBusiness();
                business.SetUserAuth(ViewBag.UserAuth);

                alert = business.Preview(model);
            }

            TempData["AlertMessage"] = alert;

            if (alert.Data != null)
            {
                TempData["ImportSales"] = alert.Data;

                return View(alert.Data);
            }
            else
            {
                return RedirectToAction("Import");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ImportSales(ImportSalesViewModel model)
        {
            AlertMessage alert = new AlertMessage();

            model = null;

            if (TempData["ImportSales"] != null)
            {
                model = TempData["ImportSales"] as ImportSalesViewModel;
            }
            else
            {
                alert.Text = StaticMessage.ERR_INVALID_INPUT;
            }

            if (model != null)
            {
                HierSalesBusiness business = new HierSalesBusiness(new SmtpService());
                business.SetUserAuth(ViewBag.UserAuth);

                alert = await business.ImportSales(model);
            }

            TempData["AlertMessage"] = alert;

            return RedirectToAction("Index");
        }

        public ActionResult DownloadTemplate()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory;
            path = Path.Combine(path, "DocTemplate", "UploadTemplate", "template-hirarkisales.xlsx");

            if (!System.IO.File.Exists(path))
            {
                return RedirectToAction("Index", "Dashboard");
            }

            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = Path.GetFileName(path);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

AIDA.Master.Web/Controllers/HierTagihController.cs
using AIDA.Master.Infrastucture.Constants;
using AIDA.Master.Service.Businesses;
using AIDA.Master.Service.Localizations;
using AIDA.Master.Service.Models;
using AIDA.Master.Web.Attributes;
using AIDA.Master.Web.Filters;
using Radyalabs.Core.Helper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AIDA.Master.Web.Controllers
{
    [AuthenticationActionFilter(ModuleCode.MasterTagihHier)]
    public class HierTagihController : Controller
    {
        public ActionResult Index()
        {
            HierTagihBusiness business = new HierTagihBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            ViewBag.IsEditable = business.IsEditable();

            return View();
        }

        [HttpPost]
        public ActionResult DatatableIndex(JDatatableViewModel model)
        {
            if (!Request.IsAjaxRequest())
            {
                return RedirectToAction("Index");
            }

            JDatatableResponse resp = new JDatatableResponse();

            HierTagihBusiness business = new HierTagihBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            resp = business.GetDatatableByQuery(model);

            return new MyJsonResult(resp, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Rayon(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }

            ViewBag.Rayon = id;

            return View();
        }

        [HttpPost]
        public ActionResult DatatableRayon(RayonDatatableViewModel model)
        {
            if (!Request.IsAjaxRequest())
            {
                return RedirectToAction("Index");
            }

            JDatatableResponse resp = new JDatatableResponse();

            HierTagihBusiness business = new HierTagihBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            resp = business.GetDatatableCustomer(model);

            return new MyJsonResult(resp, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ExportTagih(JDatatableViewModel model)
        {
            HierTagihBusiness business = new HierTagihBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            AlertMessage alert = business.ExportTagihToExcel(model);

            if (alert.Status == 1)
            {
                var bytes = alert.Data as byte[];

                return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, string.Format("HirarkiTagih-{0}.xlsx", DateTime.UtcNow.ToUtcID().ToString("yyyyMMdd-HHmm")));
            }

            return RedirectToAction("Index");
        }

        public ActionResult ImportTagih()
        {
            HierTagihBusiness business = new HierTagihBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            if (!business.IsEditable())
            {
                TempData["AlertMessage"] = new AlertMessage(StaticMessage.ERR_ACCESS_DENIED);

                return RedirectToAction("Index");
            }

            List<HierSalesViewModel> model = null;

            if (TempData["_Data"] != null)
            {
                model = TempData["_Data"] as List<HierSalesViewModel>;
            }

            return View(model);
        }

        public ActionResult PreviewImportTagih()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PreviewImportTagih(ImportTagihViewModel model)
        {
            AlertMessage alert = new AlertMessage();

            if (!ModelState.IsValid)
            {
                alert.Text = string.Join(System.Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
            }
            else
            {
                HierTagihBusiness business = new HierTagihBusiness();
                business.SetUserAuth(ViewBag.UserAuth);

                alert = business.Preview(model);
            }

            TempData["AlertMessage"] = alert;

            if (alert.Data != null)
            {
                TempData["ImportTagih"] = alert.Data;

                return View(alert.Data);
            }
            else
            {
                return RedirectToAction("ImportTagih");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ImportTagih(ImportTagihViewModel model)
        {
            AlertMessage alert = new AlertMessage();

            model = null;

            if (TempData["ImportTagih"] != null)
            {
                model = TempData["ImportTagih"] as ImportTagihViewModel;
            }
            else
            {
                alert.Text = StaticMessage.ERR_INVALID_INPUT;
            }

            if (model != null)
            {
                HierTagihBusiness business = new HierTagihBusiness();
                business.SetUserAuth(ViewBag.UserAuth);

                alert = business.ImportTagih(model);
            }

            TempData["AlertMessage"] = alert;

            return RedirectToAction("Index");
        }

        public ActionResult DownloadTemplate()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory;
            path = Path.Combine(path, "DocTemplate", "UploadTemplate", "template-hirarkitagih.xlsx");

            if (!System.IO.File.Exists(path))
            {
                return RedirectToAction("Index", "Dashboard");
            }

            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = Path.GetFileName(path);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

AIDA.Master.Web/Controllers/UtilityController.cs
using AIDA.Master.Infrastucture.Constants;
using AIDA.Master.Web.Filters;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AIDA.Master.Web.Controllers
{
    [AuthenticationActionFilter(null)]
    public class UtilityController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DownloadWI()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory;
            path = Path.Combine(path, "DocTemplate", "WI");

            //if (RoleCode.BUM.Equals(ViewBag.UserAuth.RoleCode))
            //{
            //    path = Path.Combine(path, "AIDAMaster-WI-BUM.docx");
            //}
            if (RoleCode.NSM.Equals(ViewBag.UserAuth.RoleCode))
            {
                path = Path.Combine(path, "AIDAMaster-WI-NSM.docx");
            }
            else if (RoleCode.RM.Equals(ViewBag.UserAuth.RoleCode))
            {
                path = Path.Combine(path, "AIDAMaster-WI-RM.docx");
            }
            else if (RoleCode.ASM.Equals(ViewBag.UserAuth.RoleCode))
            {
                path = Path.Combine(path, "AIDAMaster-WI-ASM.docx");
            }
            else if (RoleCode.FSS.Equals(ViewBag.UserAuth.RoleCode))
            {
                path = Path.Combine(path, "AIDAMaster-WI-Supervisor.docx");
            }
            else if (RoleCode.KaCab.Equals(ViewBag.UserAuth.RoleCode))
            {
                path = Path.Combine(path, "AIDAMaster-WI-KaCab.docx");
            }
            else if (RoleCode.AdminOperation.Equals(ViewBag.UserAuth.RoleCode))
            {
                path = Path.Combine(path, "AIDAMaster-WI-AdminOpr.docx");
            }

            if (!System.IO.File.Exists(path))
            {
                return RedirectToAction("Index", "Dashboard");
            }

            try
            {
                byte[] fileBytes = System.IO.File.ReadAllBytes(path);
                string fileName = Path.GetFileName(path);

                return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Dashboard");
            }
        }
    }
}

AIDA.Master.Web/Views/Shared/_FlashMessage.cshtml
@using Radyalabs.Core.Helper
@using AIDA.Master.Service.Models
@{
    AlertMessage alert = TempData["AlertMessage"] as AlertMessage;
}

<div class="alert-wrapper">
    @if (alert != null && ! string.IsNullOrEmpty(alert.Text))
    {
        <div class="alert @(alert.Status == 0 ? "alert-danger" : "alert-success")">
            <button class="close" data-close="alert"></button>
            @(Html.Raw(string.IsNullOrEmpty(alert.Text) ? "" : TextHelper.ConvertToHtmlNewLine(alert.Text)))
        </div>
    }
</div>

AIDA.Master.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        #loading-indicator {
            position: fixed;
            z-index: 999;
            overflow: visible;
            margin: auto;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <img src="~/Assets/custom/img/loading.gif" id="loading-indicator" style="display:none" />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AIDA.Master.Web/Views/Shared/_LayoutBody.cshtml
@using Radyalabs.Core.Helper

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title | AIDA Master</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="@SiteHelper.GetBaseUrl()Assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="@SiteHelper.GetBaseUrl()Assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="@SiteHelper.GetBaseUrl()Assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="@SiteHelper.GetBaseUrl()Assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    @RenderSection("PageStyle", required: false)
    <!-- END PAGE LEVEL SCRIPTS -->
    <!-- BEGIN THEME STYLES -->
    <link href="@SiteHelper.GetBaseUrl()Assets/global/css/components.css" id="style_components" rel="stylesheet" type="text/css" />
    <link href="@SiteHelper.GetBaseUrl()Assets/global/css/plugins.css" rel="stylesheet" type="text/css" />
    <link href="@SiteHelper.GetBaseUrl()Assets/admin/layout/css/layout.css" rel="stylesheet" type="text/css" />
    <link id="style_color" href="@SiteHelper.GetBaseUrl()Assets/admin/layout/css/themes/darkblue.css" rel="stylesheet" type="text/css" />
    <link href="@SiteHelper.GetBaseUrl()Assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css" />
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico" />
</head>
<!-- END HEAD -->
@RenderBody()
</html>

AIDA.Master.Web/Views/Shared/_SidebarAdmin.cshtml
@using Radyalabs.Core
@using AIDA.Master.Service.Models
@using AIDA.Master.Infrastucture.Constants
@{
    UserAuthenticated userAuth = ViewBag.UserAuth as UserAuthenticated;

    List<SidebarMenuModel> listMenu = new List<SidebarMenuModel>();

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "dashboard",
        Title = "Dashboard",
        Module = null,
        Icon = "icon-home",
        Url = Url.Action("Index", "Dashboard")
    });

    //if ("NSM".Equals(ViewBag.UserAuth.RoleCode))
    //{
    //    listMenu.Add(new SidebarMenuModel()
    //    {
    //        Id = "report|incentive-sales",
    //        Title = "Incentive Sales",
    //        Module = ModuleCode.IncentiveSales,
    //        Icon = "icon-trophy",
    //        Url = Url.Action("Index", "IncentiveSales")
    //    });

    //    listMenu.Add(new SidebarMenuModel()
    //    {
    //        Id = "report|incentive-collection",
    //        Title = "Incentive Collection",
    //        Module = ModuleCode.IncentiveCollection,
    //        Icon = "icon-social-dropbox",
    //        Url = Url.Action("Index", "IncentiveCollection")
    //    });
    //}

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "report",
        Title = "Report",
        Module = ModuleCode.Report,
        Icon = "icon-grid",
        Url = "javascript:void(0)",
        ListSubMenu = new List<SidebarMenuModel>()
        {
            new SidebarMenuModel()
            {
                Id = "incentive-sales",
                Title = "Incentive Sales",
                Module = ModuleCode.IncentiveSales,
                Url = Url.Action("Index", "IncentiveSales")
            },
            new SidebarMenuModel()
            {
                Id = "incentive-collection",
                Title = "Incentive Collection",
                Module = ModuleCode.IncentiveCollection,
                Url = Url.Action("Index", "IncentiveCollection")
            },
            new SidebarMenuModel()
            {
                Id = "incentive-collection-col",
                Title = "Incentive Collection : Collector",
                Module = ModuleCode.IncentiveCollectionCollector,
                Url = Url.Action("Index", "IncentiveCollectionCollector")
            },
            new SidebarMenuModel()
            {
                Id = "incentive-collection-fak",
                Title = "Incentive Collection : Fakturis",
                Module = ModuleCode.IncentiveCollectionFakturis,
                Url = Url.Action("Index", "IncentiveCollectionFakturis")
            },
            new SidebarMenuModel()
            {
                Id = "incentive-collection-spv",
                Title = "Incentive Collection :<br/>SPV Fakturis",
                Module = ModuleCode.IncentiveCollectionSPVFakturis,
                Url = Url.Action("Index", "IncentiveCollectionSPVFakturis")
            }
        }
    });

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "mastersales",
        Title = "Master Sales",
        Module = ModuleCode.MasterSales,
        Icon = "icon-basket-loaded",
        Url = "javascript:;",
        ListSubMenu = new List<SidebarMenuModel>()
        {
            new SidebarMenuModel()
            {
                Id = "mastersales-hier",
                Title = "Hirarki",
                Module = ModuleCode.MasterSalesHier,
                Url = Url.Action("Index", "HierSales")
            },
            new SidebarMenuModel()
            {
                Id = "mastersales-list",
                Title = "Master List",
                Module = ModuleCode.MasterSalesList,
                Url = Url.Action("Index", "MasterListSales")
            },
            new SidebarMenuModel()
            {
                Id = "mastersales-target",
                Title = "Target Sales",
                Module = ModuleCode.MasterSalesTarget,
                Url = Url.Action("Index", "TargetSales")
            }
        }
    });

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "mastertagih",
        Title = "Master Tagih",
        Module = ModuleCode.MasterTagih,
        Icon = "icon-handbag",
        Url = "javascript:;",
        ListSubMenu = new List<SidebarMenuModel>()
        {
            new SidebarMenuModel()
            {
                Id = "mastertagih-hier",
                Title = "Hirarki",
                Module = ModuleCode.MasterTagihHier,
                Url = Url.Action("Index", "HierTagih")
            },
            new SidebarMenuModel()
            {
                Id = "mastertagih-list",
                Title = "Master List",
                Module = ModuleCode.MasterTagihList,
                Url = Url.Action("Index", "MasterListTagih")
            }
        }
    });

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "asm",
        Title = "ASM",
        Module = ModuleCode.ASM,
        Icon = "icon-user",
        Url = Url.Action("Index", "ASM")
    });

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "supervisor",
        Title = "Supervisor",
        Module = ModuleCode.Supervisor,
        Icon = "icon-user",
        Url = Url.Action("Index", "Supervisor")
    });

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "salesman",
        Title = "Salesman",
        Module = ModuleCode.Salesman,
        Icon = "icon-user",
        Url = Url.Action("Index", "Salesman")
    });

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "collector",
        Title = "Collector",
        Module = ModuleCode.Collector,
        Icon = "icon-user",
        Url = Url.Action("Index", "Collector")
    });

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "fakturis",
        Title = "Fakturis",
        Module = ModuleCode.Fakturis,
        Icon = "icon-user",
        Url = Url.Action("Index", "Fakturis")
    });

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "spvfakturis",
        Title = "SPV Fakturis",
        Module = ModuleCode.SPVFakturis,
        Icon = "icon-user",
        Url = Url.Action("Index", "SPVFakturis")
    });

    //listMenu.Add(new SidebarMenuModel()
    //{
    //    Id = "import-collection",
    //    Title = "Upload Collection",
    //    Module = ModuleCode.ImportCollection,
    //    Icon = " icon-book-open",
    //    Url = Url.Action("Index", "Collection")
    //});

    listMenu.Add(new SidebarMenuModel()
    {
        Id = "wi",
        Title = "Working Instruction",
        Module = ModuleCode.WorkingInstruction,
        Icon = " icon-book-open",
        Url = Url.Action("DownloadWI", "Utility")
    });

    string[] arrActiveMenu = new string[] { };

    if (ViewBag.ActiveMenu != null)
    {
        arrActiveMenu = ViewBag.ActiveMenu.Split('|');
    }
}
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            <li class="sidebar-search-wrapper">
                <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
                <form class="sidebar-search"></form>
                <!-- END RESPONSIVE QUICK SEARCH FORM -->
            </li>
            @foreach (var menu in listMenu)
            {
                if (string.IsNullOrEmpty(menu.Module)
                    || (userAuth.ListModule != null && userAuth.ListModule.Exists(x => x.Equals(menu.Module))))
                {
                    <li class="@(arrActiveMenu.Length > 0 && (menu.Id.Equals(ViewBag.ActiveMenu) || menu.Id.Equals(arrActiveMenu[0])) ? "open active" : "")">
                        <a href="@menu.Url">
                            <i class="@menu.Icon"></i>
                            <span class="title">@Html.Raw(menu.Title)</span>
                            @if (menu.Id.Equals(ViewBag.ActiveMenu))
                            {
                                <span class="selected"></span>
                            }
                        </a>
                        @if (menu.ListSubMenu != null && menu.ListSubMenu.Count > 0)
                        {
                        <ul class="sub-menu">
                            @foreach (var submenu in menu.ListSubMenu)
                            {
                                if (string.IsNullOrEmpty(submenu.Module)
                                    || (userAuth.ListModule != null && userAuth.ListModule.Exists(x => x.Equals(submenu.Module))))
                                {
                                    <li class="@(arrActiveMenu.Length > 1 && submenu.Id.Equals(arrActiveMenu[1]) ? "active" : "")">
                                        <a href="@submenu.Url">@Html.Raw(submenu.Title)</a>
                                    </li>
                                }
                            }
                        </ul>
                        }
                    </li>
                }
            }
        </ul>
    </div>
</div>
<!-- END SIDEBAR -->