AIDA.Master.Web/Controllers/MasterListTagihController.cs
using AIDA.Master.Infrastucture.Constants;
using AIDA.Master.Service.Businesses;
using AIDA.Master.Service.Localizations;
using AIDA.Master.Service.Models;
using AIDA.Master.Web.Attributes;
using AIDA.Master.Web.Filters;
using Radyalabs.Core.Helper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AIDA.Master.Web.Controllers
{
    [AuthenticationActionFilter(ModuleCode.MasterTagihList)]
    public class MasterListTagihController : Controller
    {
        public ActionResult Index(string rayon)
        {
            MasterListBusiness business = new MasterListBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            ViewBag.ListRayon = business.GetRayonTagihByQuery();
            ViewBag.SelectedRayon = rayon;
            ViewBag.IsEditable = business.IsEditableTagih();

            return View();
        }

        public ActionResult CheckDouble()
        {
            return View();
        }

        public ActionResult Import()
        {
            MasterListBusiness business = new MasterListBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            if (! business.IsEditableTagih())
            {
                TempData["AlertMessage"] = new AlertMessage(StaticMessage.ERR_ACCESS_DENIED);

                return RedirectToAction("Index");
            }

            MasterImportViewModel model = null;

            if (TempData["ImportMasterList"] != null)
            {
                model = TempData["ImportMasterList"] as MasterImportViewModel;
            }

            return View(model);
        }

        public ActionResult Preview()
        {
            return RedirectToAction("Index");
        }

        public ActionResult DownloadTemplate()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory;
            path = Path.Combine(path, "DocTemplate", "UploadTemplate", "template-masterlist.xlsx");

            if (!System.IO.File.Exists(path))
            {
                return RedirectToAction("Index", "Dashboard");
            }

            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = Path.GetFileName(path);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        [HttpPost]
        public ActionResult Datatable(RayonDatatableViewModel model)
        {
            if (!Request.IsAjaxRequest())
            {
                return RedirectToAction("Index");
            }

            JDatatableResponse resp = new JDatatableResponse();

            MasterListBusiness business = new MasterListBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            resp = business.GetDatatableTagihByQuery(model);

            return new MyJsonResult(resp, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Export(RayonDatatableViewModel model)
        {
            MasterListBusiness business = new MasterListBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            AlertMessage alert = business.ExportMasterListTagih(model);

            if (alert.Status == 1)
            {
                var bytes = alert.Data as byte[];

                return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, string.Format("MasterListTagih-{0}.xlsx", DateTime.UtcNow.ToUtcID().ToString("yyyyMMdd-HHmm")));
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Preview(ImportMasterListViewModel model)
        {
            AlertMessage alert = new AlertMessage();

            if (!ModelState.IsValid)
            {
                alert.Text = string.Join(System.Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
            }
            else
            {
                MasterListBusiness business = new MasterListBusiness();
                business.SetUserAuth(ViewBag.UserAuth);

                alert = business.PreviewTagih(model);
            }

            TempData["AlertMessage"] = alert;

            if (alert.Data != null)
            {
                TempData["ImportMasterList"] = alert.Data;

                return View(alert.Data);
            }
            else
            {
                return RedirectToAction("Import");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Import(ImportMasterListViewModel model)
        {
            AlertMessage alert = new AlertMessage();

            model = null;

            if (TempData["ImportMasterList"] != null)
            {
                model = TempData["ImportMasterList"] as ImportMasterListViewModel;
            }

            if (model != null)
            {
                MasterListBusiness business = new MasterListBusiness();
                business.SetUserAuth(ViewBag.UserAuth);

                alert = business.ImportTagih(model);
            }

            else
            {
                alert.Text = StaticMessage.ERR_INVALID_INPUT;
            }

            TempData["AlertMessage"] = alert;

            return RedirectToAction("Index");
        }
    }
}

AIDA.Master.Web/Views/MasterListTagih/CheckDouble.cshtml
@using Radyalabs.Core.Helper
@{
    ViewBag.Title = "Master List Tagih Double";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.ActiveMenu = "mastertagih|mastertagih-list";
}

@section PageStyle{
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
}

@section PageScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
}

@section CustomScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/custom/js/_master-list-sales-check-double.js"></script>
}

<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Daftar Master List Tagih Double
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@SiteHelper.GetBaseUrl()"><i class="fa fa-home"></i></a>
            <a href="@Url.Action("Index", "MasterListTagih")">Master List Tagih</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="@Url.Action("CheckDouble", "MasterListTagih")">Cek Double</a>
        </li>
    </ul>
    <div class="page-toolbar">
    </div>
</div>
<!-- END PAGE HEADER-->
@Html.Partial("_FlashMessage")
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <div id="datatable-filter-rayon" style="display: none">
            @if (ViewBag.ListRayon != null && ViewBag.ListRayon.Count > 0)
            {
                <label>Rayon:&nbsp; </label>
                <select class="form-control input-inline input-small" name="RayonCode">
                    <option value="">- semua -</option>
                    @foreach (var item in ViewBag.ListRayon)
                    {
                        <option value="@item.RayonCode" @(item.RayonCode.Equals(ViewBag.SelectedRayon) ? "selected" : "")>@item.RayonCode</option>
                    }
                </select>
            }
        </div>
        <table class="datatable table table-striped table-bordered table-hover" data-rayon="@ViewBag.Rayon">
            <thead>
                <tr>
                    <th rowspan="2">#</th>
                    <th rowspan="2" style="text-align: center">Rayon</th>
                    <th colspan="2" style="text-align: center">Salesman</th>
                    <th colspan="2" style="text-align: center">Customer</th>
                    <th colspan="2" style="text-align: center">Valid</th>
                </tr>
                <tr>
                    <th>NIK</th>
                    <th>Nama</th>
                    <th>Kode</th>
                    <th>Nama</th>
                    <th>Dari</th>
                    <th>Sampai</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
<!-- END PAGE CONTENT-->

AIDA.Master.Web/Views/MasterListTagih/Import.cshtml
@using Radyalabs.Core.Helper
@model AIDA.Master.Service.Models.MasterImportViewModel
@{
    ViewBag.Title = "Upload Master List Tagih";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.ActiveMenu = "mastertagih|mastertagih-list";
}

@section PageStyle{
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" />
}

@section PageScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/jquery-validation/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/jquery-validation/js/additional-methods.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
}

@section CustomScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/custom/js/_master-list-sales-import.js"></script>
}

<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Upload Master List Tagih <small>upload excel</small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@SiteHelper.GetBaseUrl()"><i class="fa fa-home"></i></a>
            <a href="@Url.Action("Index", "MasterListTagih")">Master List Tagih</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="@Url.Action("Import", "MasterListTagih")">Upload</a>
        </li>
    </ul>
    <div class="page-toolbar">
    </div>
</div>
<!-- END PAGE HEADER-->
@Html.Partial("_FlashMessage")
<div class="portlet box blue">
    <div class="portlet-body form">
        <form id="main-form" class="form-horizontal" role="form" action="@Url.Action("Preview", "MasterListTagih")" method="post" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-4">
                        <a class="" href="@Url.Action("DownloadTemplate", "MasterListTagih")"><i class="fa fa-download" aria-hidden="true"></i> download template</a>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Valid Mulai<i class="required">*</i></label>
                    <div class="col-md-4">
                        <input class="form-control datepicker input-small" type="text" name="FormattedValidDate" readonly>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">File<i class="required">*</i></label>
                    <div class="col-md-4">
                        <input type="file" name="InputFile">
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn blue">Preview</button>
                        <a href="@Url.Action("Index", "MasterListTagih")" class="btn default">Kembali</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

AIDA.Master.Web/Views/MasterListTagih/Index.cshtml
@using Radyalabs.Core.Helper
@{
    ViewBag.Title = "Master List Tagih";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.ActiveMenu = "mastertagih|mastertagih-list";
}

@section PageStyle{
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/select2/select2.css" />
}

@section PageScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/select2/select2.js"></script>
}

@section CustomScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/custom/js/_master-list-tagih-index.js"></script>
}

<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Master List Tagih
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@SiteHelper.GetBaseUrl()"><i class="fa fa-home"></i></a>
            <a href="@Url.Action("Index", "MasterListTagih")">Master List Tagih</a>
        </li>
    </ul>
    <div class="page-toolbar">
        @if (ViewBag.IsEditable)
        {
            <a id="btn-import" href="@Url.Action("Import", "MasterListTagih")" class="btn btn-fit-height btn-sm green-stripe" data-container="body" data-placement="left" data-original-title="" title="">
                    <i class="fa fa-cloud-upload" aria-hidden="true"></i> Upload
                </a>
        }
        <a id="btn-export-excel" class="btn btn-fit-height btn-sm green-stripe" disabled>
            <i class="fa fa-file-excel-o"></i> Download
        </a>
        <form id="form-export-excel" method="post" action="@Url.Action("Export", "MasterListTagih")" target="_blank">
            <input type="hidden" name="Keyword" value="" />
            <input type="hidden" name="Length" value="" />
            <input type="hidden" name="Start" value="" />
            <input type="hidden" name="IndexOrderCol" value="" />
            <input type="hidden" name="OrderType" value="" />
            <input type="hidden" name="RayonCode" value="" />
        </form>
    </div>
</div>
<!-- END PAGE HEADER-->
@Html.Partial("_FlashMessage")
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <div id="datatable-filter-rayon" style="display: none">
            @if (ViewBag.ListRayon != null && ViewBag.ListRayon.Count > 0)
            {
                <label>Rayon/Salesman:&nbsp; </label>
                <select class="form-control input-inline input-large" name="RayonCode">
                    <option value="">- semua -</option>
                    @foreach (var item in ViewBag.ListRayon)
                    {
                        <option value="@item.RayonCode" @(item.RayonCode.Equals(ViewBag.SelectedRayon) ? "selected" : "")>@(item.RayonCode + " - " + item.SalesmanFullname)</option>
                    }
                </select>
            }
        </div>
        <table class="datatable table table-striped table-bordered table-hover table-nowrap" data-rayon="@ViewBag.Rayon">
            <thead>
                <tr>
                    <th rowspan="2">#</th>
                    <th colspan="2" style="text-align: center">Customer</th>
                    <th rowspan="2" style="text-align: center">Rayon</th>
                    <th colspan="2" style="text-align: center">Salesman</th>
                    <th colspan="2" style="text-align: center">Supervisor</th>
                    <th colspan="2" style="text-align: center">Valid</th>
                </tr>
                <tr>
                    <th>Kode</th>
                    <th>Nama</th>
                    <th>NIK</th>
                    <th>Nama</th>
                    <th>NIK</th>
                    <th>Nama</th>
                    <th>Dari</th>
                    <th>Sampai</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
<!-- END PAGE CONTENT-->

AIDA.Master.Web/Views/MasterListTagih/Preview.cshtml
@using Radyalabs.Core.Helper
@model AIDA.Master.Service.Models.ImportMasterListViewModel
@{
    ViewBag.Title = "Upload Master List Tagih";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.ActiveMenu = "mastertagih|mastertagih-list";

    int numError = Model.ListCustomer.Count(x=>!string.IsNullOrEmpty(x.Remarks));
}

@section PageStyle{
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
}

@section PageScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/jquery-validation/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
}

@section CustomScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/custom/js/_master-list-sales-preview.js"></script>
}

<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Preview Upload Master List Tagih
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@SiteHelper.GetBaseUrl()"><i class="fa fa-home"></i></a>
            <a href="@Url.Action("Index", "MasterListTagih")">Master List Tagih</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="@Url.Action("Import", "MasterListTagih")">Upload</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="javascript:;">Preview</a>
        </li>
    </ul>
    <div class="page-toolbar">
        <a id="btn-submit-preview" class="btn btn-fit-height btn-sm blue" @(numError > 0 ? "disabled" : "")>
            <i class="fa fa-save"></i> Submit
        </a>
    </div>
</div>
<!-- END PAGE HEADER-->
@Html.Partial("_FlashMessage")
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption">
            Valid Mulai : @Model.FormattedValidDate
        </div>
    </div>
    <div class="portlet-body">
        <table class="datatable table table-striped table-bordered table-hover table-nowrap">
            <thead>
                <tr>
                    <th class="text-right">
                        #
                    </th>
                    <th style="text-align: center;">
                        Rayon<br />Code
                    </th>
                    <th style="text-align: center;">
                        NIK<br />Salesman
                    </th>
                    <th>
                        Nama<br />Salesman
                    </th>
                    <th style="text-align: center;">
                        Kode<br />Customer
                    </th>
                    <th>
                        Nama<br />Customer
                    </th>
                    <th>
                        Keterangan
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ListCustomer != null)
                {
                    int i = 1;
                    foreach (var item in Model.ListCustomer)
                    {
                        <tr class="@(! string.IsNullOrEmpty(item.Remarks) ? "bg-red-intense" : "")">
                            <td align="right">@i</td>
                            <td align="center">@item.RayonCode</td>
                            <td align="center">@item.SLMNik</td>
                            <td align="left">@item.SLMFullname</td>
                            <td align="center">@item.CustomerCode</td>
                            <td align="left">@item.CustomerName</td>
                            <td align="left">@item.Remarks</td>
                        </tr>
                        i++;
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<div id="modal-confirmation" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
    <form id="form-confirmation" class="modal-dialog modal-sm" method="post" action="@Url.Action("Import", "MasterListTagih")">
        @Html.AntiForgeryToken()
        @*<input type="hidden" name="Id" value="@Model.Id" />*@
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Apakah yakin upload data ini?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn default">tidak</button>
                <button type="submit" class="btn blue">ya</button>
            </div>
        </div>
    </form>
</div>