AIDA.Master.Web/Controllers/ASMController.cs
using AIDA.Master.Infrastucture.Constants;
using AIDA.Master.Service.Businesses;
using AIDA.Master.Service.Localizations;
using AIDA.Master.Service.Models;
using AIDA.Master.Web.Attributes;
using AIDA.Master.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AIDA.Master.Web.Controllers
{
    [AuthenticationActionFilter(ModuleCode.ASM)]
    public class ASMController : Controller
    {
        public ActionResult Index()
        {
            ASMBusiness business = new ASMBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            ViewBag.IsEditable = business.IsEditable();

            return View();
        }

        public ActionResult Add()
        {
            ASMBusiness business = new ASMBusiness();

            ViewBag.ListRayonType = business.GetListRayonType();

            return View("Edit", new ASMViewModel());
        }

        public ActionResult Edit(int? id = null)
        {
            ViewBag.IsEdit = true;

            if (id == null)
            {
                return RedirectToAction("Index");
            }

            ASMBusiness business = new ASMBusiness();

            ASMViewModel model = business.GetDetail(id.Value);

            if (model == null)
            {
                TempData["AlertMessage"] = new AlertMessage(StaticMessage.ERR_DATA_NOT_FOUND);

                return RedirectToAction("Index");
            }

            ViewBag.ListRayonType = business.GetListRayonType();

            return View(model);
        }

        [HttpPost]
        public ActionResult Datatable(JDatatableViewModel model)
        {
            if (!Request.IsAjaxRequest())
            {
                return RedirectToAction("Index");
            }

            JDatatableResponse resp = new JDatatableResponse();

            ASMBusiness business = new ASMBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            resp = business.GetDatatableByQuery(model);

            return new MyJsonResult(resp, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ASMViewModel model)
        {
            AlertMessage alert = new AlertMessage();

            ASMBusiness business = new ASMBusiness();

            if (!ModelState.IsValid)
            {
                alert.Text = string.Join(System.Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
            }
            else
            {
                business.SetUserAuth(ViewBag.UserAuth);

                alert = business.Add(model);
            }

            TempData["AlertMessage"] = alert;

            if (alert.Status == 1)
            {
                return RedirectToAction("Index");
            }

            ViewBag.ListRayonType = business.GetListRayonType();

            return View("Edit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ASMViewModel model)
        {
            ViewBag.IsEdit = true;

            AlertMessage alert = new AlertMessage();

            ASMBusiness business = new ASMBusiness();

            if (!ModelState.IsValid)
            {
                alert.Text = string.Join(System.Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
            }
            else
            {
                business.SetUserAuth(ViewBag.UserAuth);

                alert = business.Edit(model);
            }

            TempData["AlertMessage"] = alert;

            if (alert.Status == 1)
            {
                return RedirectToAction("Index");
            }

            ViewBag.ListRayonType = business.GetListRayonType();

            return View("Edit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateAccess(ASMUpdateAccessViewModel model)
        {
            if (!Request.IsAjaxRequest())
            {
                return RedirectToAction("Index");
            }

            AlertMessage alert = new AlertMessage();

            ASMBusiness business = new ASMBusiness();

            if (!ModelState.IsValid)
            {
                alert.Text = string.Join(System.Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
            }
            else
            {
                business.SetUserAuth(ViewBag.UserAuth);

                alert = business.UpdateAccess(model);
            }

            return new MyJsonResult(alert, JsonRequestBehavior.AllowGet);
        }
    }
}

AIDA.Master.Web/Views/ASM/Edit.cshtml
@using Radyalabs.Core.Helper
@model AIDA.Master.Service.Models.ASMViewModel
@{
    ViewBag.Title = (ViewBag.IsEdit == null ? "Tambah" : "Edit") + " ASM";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.ActiveMenu = "fakturis";
}

@section PageStyle{
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" />
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/select2/select2.css" />
}

@section PageScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/jquery-validation/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/select2/select2.js"></script>
}

@section CustomScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/custom/js/_asm-edit.js"></script>
}

<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    @(ViewBag.IsEdit == null ? "Tambah" : "Edit") ASM
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@SiteHelper.GetBaseUrl()"><i class="fa fa-home"></i></a>
            <a href="@Url.Action("Index", "ASM")">ASM</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="@Url.Action((ViewBag.IsEdit == null ? "Add" : "Edit"), "ASM")">Tambah</a>
        </li>
    </ul>
    <div class="page-toolbar">
    </div>
</div>
<!-- END PAGE HEADER-->
@Html.Partial("_FlashMessage")
<div class="portlet box blue">
    <div class="portlet-body form">
        <form id="main-form" class="form-horizontal" role="form" action="@Url.Action((ViewBag.IsEdit == null ? "Add" : "Edit"), "ASM")" method="post">
            @Html.AntiForgeryToken()
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">NIK<i class="required">*</i></label>
                    <div class="col-md-4">
                        <input class="form-control" type="text" name="NIK" value="@(Model.NIK == 0 ? "" : Model.NIK.ToString())" @(ViewBag.IsEdit != null ? "readonly" : "")>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Nama<i class="required">*</i></label>
                    <div class="col-md-4">
                        <input class="form-control" type="text" name="Fullname" value="@Model.Fullname">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Tipe Rayon (Default)<i class="required">*</i></label>
                    <div class="col-md-4">
                        <select class="form-control select2" name="DefaultRayonType">
                            <option value=""></option>
                            @if (ViewBag.ListRayonType != null)
                            {
                                foreach (var item in ViewBag.ListRayonType)
                                {
                                    <option value="@item.RayonType" @(item.RayonType.Equals(Model.DefaultRayonType) ? "selected" : "")>@(item.RayonType)</option>
                                }
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-4">
                        <div class="checkbox-list">
                            <label class="checkbox-inline">
                                <input type="checkbox" value="true" name="IsRole" @(Model.IsRole ? "checked" : "")> Jabatan ASM?
                            </label>
                        </div>
                    </div>
                </div>
                @if (ViewBag.IsEdit != null)
                {
                    <div class="form-group">
                        <label class="col-md-3 control-label">Valid<i class="required">*</i></label>
                        <div class="col-md-9">
                            <div class="input-group date-picker input-large input-daterange" data-date-format="yyyy-mm-dd">
                                <input class="form-control input-date" name="FormattedValidFrom" value="@Model.FormattedValidFrom" type="text">
                                <span class="input-group-addon">&nbsp;sampai&nbsp;</span>
                                <input class="form-control input-date" name="FormattedValidTo" value="@(string.IsNullOrEmpty(Model.FormattedValidTo) ? "9999-12-31" : Model.FormattedValidTo )" type="text">
                            </div>
                        </div>
                    </div>
                }

            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn blue">Submit</button>
                        <a href="@Url.Action("Index", "ASM")" class="btn default">Kembali</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

AIDA.Master.Web/Views/ASM/Index.cshtml
@using Radyalabs.Core.Helper
@using AIDA.Master.Infrastucture.Constants
@{
    ViewBag.Title = "ASM";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.ActiveMenu = "asm";
}

@section PageStyle{
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/extensions/Buttons/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" />
}

@section PageScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/extensions/Buttons/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
}

@section CustomScript{
    @if (RoleCode.KaCab.Equals(ViewBag.UserAuth.RoleCode) || RoleCode.NSM.Equals(ViewBag.UserAuth.RoleCode))
    {
        <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/custom/js/_asm-index-nsm.js"></script>
    }
    else
    {
        <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/custom/js/_asm-index.js"></script>
    }
}

<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Daftar ASM
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@SiteHelper.GetBaseUrl()"><i class="fa fa-home"></i></a>
            <a href="@Url.Action("Index", "ASM")">ASM</a>
        </li>
    </ul>
    <div class="page-toolbar">
        @if (ViewBag.IsEditable)
        {
            <a id="btn-add" href="@Url.Action("Add", "ASM")" class="btn btn-fit-height btn-sm blue-stripe" data-container="body" data-placement="left" data-original-title="" title="">
                <i class="fa fa-plus" aria-hidden="true"></i> Tambah
            </a>
        }
    </div>
</div>
<!-- END PAGE HEADER-->
@Html.Partial("_FlashMessage")
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    @Html.AntiForgeryToken()
    <div id="tbl-wrapper" class="col-md-12">
        <table class="datatable table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th rowspan="2" style="text-align: right">#</th>
                    <th rowspan="2" style="text-align: left">Action</th>
                    <th colspan="2" style="text-align: center">Upload</th>
                    <th rowspan="2" style="text-align: center">NIK</th>
                    <th rowspan="2">Nama</th>
                    <th rowspan="2" style="text-align: center">Default Rayon Type</th>
                    <th rowspan="2" style="text-align: center">ASM</th>
                    <th rowspan="2" style="text-align: center">Valid From</th>
                    <th rowspan="2" style="text-align: center">Valid To</th>
                </tr>
                <tr>
                    <th><i class="fa fa-check-circle"></i></th>
                    <th style="text-align: center; width: 100px">Sampai</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
<!-- END PAGE CONTENT-->