AIDA.Master.Web/Controllers/IncentiveCollectionSPVFakturisController.cs
using AIDA.Master.Infrastucture.Constants;
using AIDA.Master.Service.Businesses;
using AIDA.Master.Service.Models;
using AIDA.Master.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AIDA.Master.Web.Controllers
{
    [AuthenticationActionFilter(ModuleCode.IncentiveCollectionSPVFakturis)]
    public class IncentiveCollectionSPVFakturisController : Controller
    {
        public ActionResult Index()
        {
            IncentiveCollectionBusiness business = new IncentiveCollectionBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            IncentiveCollectionReportViewModel model = new IncentiveCollectionReportViewModel();

            ViewBag.ListBranch = business.GetListBranch();

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(string p, string b)
        {
            IncentiveCollectionBusiness business = new IncentiveCollectionBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            IncentiveCollectionReportViewModel model = business.GetReportSPVFakturis(p, b);

            ViewBag.ListBranch = business.GetListBranch();

            return View(model);
        }

        [HttpPost]
        public ActionResult ExportReport(string p, string b)
        {
            IncentiveCollectionBusiness business = new IncentiveCollectionBusiness();
            business.SetUserAuth(ViewBag.UserAuth);

            AlertMessage alert = business.ExportReportSPVFakturis(p, b);

            if (alert.Status == 1)
            {
                var bytes = alert.Data as byte[];

                return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, string.Format("IncentiveCollection-SPVFakturis-{0}.xlsx", p));
            }

            return RedirectToAction("Index");
        }
    }
}

AIDA.Master.Web/Views/IncentiveCollectionSPVFakturis/Index.cshtml
@using Radyalabs.Core.Helper
@using AIDA.Master.Infrastucture.Constants
@model AIDA.Master.Service.Models.IncentiveCollectionReportViewModel
@{
    ViewBag.Title = "Incentive Collection : SPV Fakturis";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.ActiveMenu = "report|incentive-collection-spv";
}

@section PageStyle{
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" />
    <link rel="stylesheet" type="text/css" href="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
}

@section PageScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/jquery-validation/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/global/plugins/select2/select2.js"></script>
}

@section CustomScript{
    <script type="text/javascript" src="@SiteHelper.GetBaseUrl()Assets/custom/js/_incentive-collection-index.js"></script>
}

<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Incentive Collection : SPV Fakturis
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@SiteHelper.GetBaseUrl()"><i class="fa fa-home"></i></a>
            <a href="@Url.Action("Index", "IncentiveCollectionSPVFakturis")">Incentive Collection : SPV Fakturis</a>
        </li>
    </ul>
    <div class="page-toolbar">
        <a id="btn-export-excel" class="btn btn-fit-height btn-sm green-stripe" href="javascript:;">
            <i class="fa fa-file-excel-o"></i> Download
        </a>
        <form id="form-export" style="display: none" target="_blank" method="post" action="@Url.Action("ExportReport", "IncentiveCollectionSPVFakturis")">
            <input type="hidden" name="p" value="@Model.FormattedMonthYear" />
        </form>
    </div>
</div>
<!-- END PAGE HEADER-->
@Html.Partial("_FlashMessage")
<div class="row">
    <div class="col-md-12">
        <form id="main-form" class="form-horizontal" role="form" action="@Url.Action("Index", "IncentiveCollectionSPVFakturis")" method="post">
            <div class="form-group">
                <label class="col-md-3 control-label">Bulan-Tahun <i class="required">*</i></label>
                <div class="col-md-2">
                    <div class="input-group input-small">
                        <input class="form-control datepicker input-small text-center" type="text" name="p" value="@Model.FormattedMonthYear" readonly>
                    </div>
                </div>
                @if (RoleCode.AdminOperation.Equals(ViewBag.UserAuth.RoleCode))
                {
                    if (ViewBag.ListBranch != null && ViewBag.ListBranch.Count > 0)
                    {
                        <label class="col-md-1 control-label">Cabang</label>
                        <div class="col-md-3">
                            <select class="form-control input-inline input-medium" name="b">
                                <option value="">- semua -</option>
                                @foreach (var item in ViewBag.ListBranch)
                                {
                                    <option value="@item.Code" @(item.Code.Equals(Model.Plant) ? "selected" : "")>@(item.Code + " - " + item.Name)</option>
                                }
                            </select>

                        </div>
                    }
                }
                <div class="col-md-1">
                    <span class="input-group-btn">
                        <button class="btn blue" type="submit"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="tabbable-custom">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#tab-slm-raw" tabindex="-1" data-toggle="tab">
                SPV Fakturis Raw
            </a>
        </li>
        <li>
            <a href="#tab-incentive-slm" tabindex="-1" data-toggle="tab">
                SPV Fakturis
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade active in" id="tab-slm-raw">
            <table class="datatable table table-striped table-bordered table-hover table-nowrap">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Description</th>
                        <th style="text-align: center">NIK</th>
                        <th>FullName</th>
                        <th style="text-align: right">Total Target Collect</th>
                        <th style="text-align: right">Total Actual Collect</th>
                        <th style="text-align: right">Percentage Collection</th>
                        <th style="text-align: right">Collection Incentive</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.ListRawData != null && Model.ListRawData.Count > 0)
                    {
                        int i = 1;
                        foreach (var item in Model.ListRawData)
                        {
                            <tr>
                                <td align="right">@i</td>
                                <td align="left">@item.Description</td>
                                <td align="center">@item.NIK</td>
                                <td align="left">@item.Fullname</td>
                                <td align="right">@item.TotalTargetCollect.ToString("N0")</td>
                                <td align="right">@item.TotalActualCollect.ToString("N0")</td>
                                <td align="right">@item.PercentageCollection.ToString("N2")</td>
                                <td align="right">@item.CollectionIncentives.ToString("N0")</td>
                            </tr>
                            i++;
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="tab-incentive-slm">
            <table class="datatable table table-striped table-bordered table-hover table-nowrap">
                <thead>
                    <tr>
                        <th>#</th>
                        <th style="text-align: center">NIK</th>
                        <th>FullName</th>
                        <th style="text-align: right">Total Incentive</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.ListSummaryData != null && Model.ListSummaryData.Count > 0)
                    {
                        int i = 1;
                        foreach (var item in Model.ListSummaryData)
                        {
                            <tr>
                                <td align="right">@i</td>
                                <td align="center">@item.NIK</td>
                                <td align="left">@item.Fullname</td>
                                <td align="right">@item.TotalIncentives.ToString("N0")</td>
                            </tr>
                            i++;
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>